### ISSUE TITLE
Can't find names?

### ISSUE THREAD

**Issue by karlp** [PeterMcKinnis/WostCaseStack#2]
Hi, I've tried running this on some cortex-m3 compiled code, with gcc 6.3, and after changing the filename match from 270r.dfinish to 290r.dfinish, I just get the exception below.

I've tried adding code to validate the section decoding, but I suspect it's just your self build elf decoder being not quite flexible enough?   Would perhaps pybfd or bfdpie perhaps provide something robust for the symbol parsing?

```
Traceback (most recent call last):
  File "/home/karlp/src/WostCaseStack/WCS.py", line 327, in <module>
    main()
  File "/home/karlp/src/WostCaseStack/WCS.py", line 308, in main
    read_tu(tu, call_graph)
  File "/home/karlp/src/WostCaseStack/WCS.py", line 164, in read_tu
    read_obj(tu, call_graph)  # This must be first
  File "/home/karlp/src/WostCaseStack/WCS.py", line 20, in read_obj
    symbols = elf.read_symbols(tu + obj_ext)
  File "/home/karlp/src/WostCaseStack/elf.py", line 35, in read_symbols
    _read_file(g)
  File "/home/karlp/src/WostCaseStack/elf.py", line 59, in _read_file
    _read_symbol_table(g)
  File "/home/karlp/src/WostCaseStack/elf.py", line 133, in _read_symbol_table
    s.name = _read_name(g, sh.link, s.name_index)
  File "/home/karlp/src/WostCaseStack/elf.py", line 89, in _read_name
    while g.content[end]:
IndexError: string index out of range
```

**Comment by PeterMcKinnis** [comment]
Its been awhile since I looked at the code.  I could take a look at it.
Are you able to share the binaries?

Regards
Peter

**Comment by karlp** [comment]
I just ran it again on one (any one) of the examples from http://github.com/libopencm3/libopencm3-examples  

I did a local patch to add the compiler flags needed
```
diff --git a/examples/stm32/l1/stm32l-discovery/button-irq-printf/Makefile b/examples/stm32/l1/stm32l-discovery/button-irq-printf/Makefile
index e2b5060..b7c351c 100644
--- a/examples/stm32/l1/stm32l-discovery/button-irq-printf/Makefile
+++ b/examples/stm32/l1/stm32l-discovery/button-irq-printf/Makefile
@@ -19,6 +19,11 @@
 
 BINARY = main
 
+TGT_CFLAGS += -fstack-usage  -Wstack-usage=50
+TGT_CFLAGS += -fdump-tree-optimized
+TGT_CFLAGS += -fdump-rtl-dfinish
+
+
 LDSCRIPT = $(OPENCM3_DIR)/lib/stm32/l1/stm32l15xxb.ld
 
 include ../../Makefile.include
```

You'd need an arm-none-eabi toolchain to build that repo, but should be perfectly good test data.

I can probably zip up the output binaries and .su and .dfinish files if you have problems though

**Comment by PeterMcKinnis** [comment]
I went ahead and removed the dependency on elf.py as requested.  I ran the example `/examples/stm32/l1/stm32l-discovery/button-irq-printf/`.  It runs fine on my machine giving the output:

```
$ python /c/Users/peter/PycharmProjects/WostCaseStack/WCS.py
Reading: main.c.270r.dfinish, main.su, main.o

Translation Unit Function Name    Stack     Unresolved Dependencies
main             _write                  24 (usart_send_blocking ,__errno)
main             exti0_isr               16 (gpio_clear ,puts ,exti_reset_request ,printf ,gpio_set ,exti_set_trigger)
main             tim6_isr                 8 (printf ,gpio_toggle)
main             main                     8 (rcc_periph_clock_enable ,usart_set_stopbits ,timer_set_period ,usart_set_baudrate ,usart_set_flow_control ,gpio_mode_setup ,puts ,rcc_periph_reset_pulse ,exti_select_source ,usart_set_parity ,exti_set_trigger ,timer_enable_irq ,rcc_clock_setup_pll ,exti_enable_request ,timer_enable_counter ,usart_enable ,usart_set_mode ,usart_set_databits ,gpio_set_af ,timer_enable_update_event ,timer_set_prescaler ,nvic_enable_irq)
```

Please let me know if it works for you too.

**Comment by karlp** [comment]
yep! nice works for me!  thanks for the awesomely quick turnaround!
